services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/socialgenius
      - DATABASE_URL_DOCKER=postgresql://postgres:postgres@postgres:5432/socialgenius
      - PG_DEBUG=true
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=your-nextauth-secret
      - NODE_ENV=development
      - BROWSER_API_URL=http://browser-use-api:5055
      - SUPPRESS_FAST_REFRESH_LOGS=true
      - NEXT_COMPILER_FILTER_WARNINGS=true
      - NODE_PG_FORCE_NATIVE=0
      - RUNNING_IN_DOCKER=true
      - NODE_OPTIONS=--require=/app/pg-constructor-fix-loader.cjs --max-old-space-size=4096
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    command: >
      sh -c "
        npm run dev
      "
    depends_on:
      postgres:
        condition: service_healthy
      browser-use-api:
        condition: service_healthy

  browser-use-api:
    build:
      context: ./browser-use-api
      dockerfile: Dockerfile
    container_name: social-genius-browser-api
    volumes:
      - ./browser-use-api/screenshots:/app/screenshots
    environment:
      - PORT=5055
      - HOST=0.0.0.0
    ports:
      - "5055:5055"
    restart: unless-stopped
    command: bash -c "pip install -r requirements.txt && python -m uvicorn server:app --host 0.0.0.0 --port 5055"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5055/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  postgres:
    image: pgvector/pgvector:pg14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=socialgenius
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_v14:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@socialgenius.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data_v14: