version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"  # Use port 8080 instead of 80 to avoid conflicts
    volumes:
      - ./src/nginx/conf/simple.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - sg_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - sg_network

networks:
  sg_network:
    driver: bridge
