version: '3.8'

services:
  # PostgreSQL with pgvector
  postgres:
    image: pgvector/pgvector:pg14
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialgenius
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - social_genius_network

  # Node.js application with PostgreSQL patches
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - pg_fixes:/app/fixes
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/socialgenius
      DATABASE_URL_DOCKER: postgresql://postgres:postgres@postgres:5432/socialgenius
      NODE_PG_FORCE_NATIVE: '0'
      PG_DEBUG: 'true'
      DEBUG_DATABASE: 'true'
      RUNNING_IN_DOCKER: 'true'
      NODE_OPTIONS: "--require=/app/pg-constructor-fix-loader.js --max-old-space-size=4096"
    depends_on:
      - postgres
    entrypoint: ["/bin/bash", "/app/pg-entry.sh"]
    networks:
      - social_genius_network
    restart: unless-stopped

  # Headless browser service for compliance checks
  browser-api:
    build:
      context: ./browser-use-api
      dockerfile: Dockerfile
    ports:
      - "5050:5000"
    volumes:
      - browser_cookies:/app/cookies
    restart: unless-stopped
    networks:
      - social_genius_network

networks:
  social_genius_network:
    driver: bridge

volumes:
  postgres_data:
  pg_fixes:
  browser_cookies:
