version: "3.9"

services:
  browser-use-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-genius-browser-api
    volumes:
      - ./screenshots:/app/screenshots
    environment:
      - PORT=5055
      - HOST=0.0.0.0
    ports:
      - "5055:5055"
    restart: unless-stopped
    command: python -m uvicorn server:app --host 0.0.0.0 --port 5055
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5055/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s